name: Scraper Google Jobs Iglubit

on:
  schedule:
    # Se ejecuta 1 vez al día a las 8:00 UTC
    # En España: 10:00 (verano) / 09:00 (invierno)
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar Scraper
        run: python scraper.py
